name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    - name: login to server and run the container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd /${{ secrets.USERNAME }}/dokalab_web_auth_service
          git pull

          npm run build

          docker compose down -v
          docker compose up -d --build
          docker image prune -f

          rover graph publish ${{ secrets.APOLLO_GRAPH_REF }} \
            --schema ./schema.gql